const express = require("express")
const user = express.Router()
const { getUserById, liveSearch, editProfile, updateDp, getLoggedInUserInfo, discoverPeople, updateCover } = require("../controllers/user.controller")
user.get("/", getUserById)
user.get("/discover-people", discoverPeople)
user.get("/loggedin-user", getLoggedInUserInfo)
user.get("/search", liveSearch)
user.patch("/edit", editProfile)
user.patch("/updatedp", updateDp)
user.patch("/updatecover", updateCover)
module.exports = user